### ISSUE TITLE
Map bonus not being applied

### ISSUE THREAD

**Issue by kuzi117** [Trimps/Trimps.github.io#13]
The values are being calculated correctly in tooltips but not being applied (i.e. I have 3B block after the bonus in tooltip but it only shows 1B, I also take damage as if I had only 1B block).

See screenshots: http://imgur.com/a/eOK2y

**Comment by QuadeHale** [comment]
Stats from anything other than equipment take until the next spawn to take effect. If your batch of trimps dies, the new stats should populate. This goes for gyms, trainers, levels of coordination, and other upgrades. I believe this is intended.
