### ISSUE TITLE
CSS issue - map settings

### ISSUE THREAD

**Issue by Deyero** [Trimps/Trimps.github.io#155]
Some adblockers consider the .advContainer panel with advanced map settings as an ad, therefore hiding it.

**Comment by giraffesyo** [comment]
Looks like a list of names to avoid: https://github.com/hynnet/openwrt-ads/blob/master/adblock-lazy.txt

**Comment by Trimps** [comment]
https://github.com/Trimps/Trimps.github.io/commit/f202879825d6670de1374fc25960f0517a21e525

Fixed, thanks!
