### ISSUE TITLE
Swap ruined my heirloom

### ISSUE THREAD

**Issue by HeadWar** [Trimps/Trimps.github.io#161]
I'm not completely sure about how this happened, but I had just gotten my third heirloom, a staff. I had a staff and a shield, both equipped, since before.

I think what I did then was, I clicked the newly aquired staff, in the Temporary box, and then clicked Swap. It might have been some other order of clicking, or maybe I had also selected the already equipped staff, but I don't think so.

I really don't want to try to get this to happen again, because instead of equipping my new staff, which was what I expected, the new staff became some sort of linked copy of the old staff. Both staffs have the same stats, and also the same name, such that if I change the name of one of the staffs, the other changes name as well.

**Comment by Trimps** [comment]
https://github.com/Trimps/Trimps.github.io/commit/5629f11f50bba8b5fea8177dd973804d1aeecffe

Fixed, thanks!
