### ISSUE TITLE
Resource Timers show "0 secs" at 1 minute

### ISSUE THREAD

**Issue by biinari** [Trimps/Trimps.github.io#20]
With 1 minute remaining to having enough resources to buy something the resource timer says "0 secs". Instead it should be one of the following

1. "1 min"
2. "1 min 0 secs"

According to the changelog, "60 secs" should never be shown now, so I presume that would not be considered as an option.

**Comment by biinari** [comment]
Seems to be fixed now.

**Comment by QuadeHale** [comment]
Please close the issue!
