### ISSUE TITLE
Enemy attack damage becomes infinite after around Zone 594

### ISSUE THREAD

**Issue by feilong** [Trimps/Trimps.github.io#21]
Well, I hacked the game a little bit to reach this zone...
I guess it's because the damage number is too large for a float number.
<img width="742" alt="screen shot" src="https://cloud.githubusercontent.com/assets/2242261/12206637/138cbdd6-b610-11e5-86ee-0c18cf45e820.png">

**Comment by subchannel13** [comment]
Standard "double precision floats" can go up to 1.7*e^308 but Javascript behavior is browser dependant so your mileage my vary. It might be fixed with some "big number" library if one exists for JS.

**Comment by QuadeHale** [comment]
Is this really an issue? Reaching this point without hacking the game would take years.
