### ISSUE TITLE
Range Perk Affects Max instead of Min Damage

### ISSUE THREAD

**Issue by Deus-Adder-Ex** [Trimps/Trimps.github.io#228]
![image](https://user-images.githubusercontent.com/22172777/104817671-47966580-57e8-11eb-87b0-b8a1cb24a490.png)

**Comment by dangercrow** [comment]
Looks fine to me - the attached image shows you had a base of:
-20%/+20%
and then after 10 levels of range, your min went up 20%, from -20% to 0%, leading to
-0%/+20%

**Comment by Deus-Adder-Ex** [comment]
Ah, it's a running total. I was expecting line items. Closing.
