### ISSUE TITLE
graph showing progress

### ISSUE THREAD

**Issue by Rubik43** [Trimps/Trimps.github.io#230]
Graphs showing trends of parameters between the runs(with last/best run): attack, life, resources, world progress ....
like in this [picture](https://lh3.googleusercontent.com/proxy/0BGnroADRUJ7eUelVYyba9FzlirPfsPet2CwDGmeGyVshtsIiQgpeILj9sCXAZeBWU-T0F8M6b6oDVsxx0jvEfjoHScDlQxP57J1ypB9kdeDrTRsiZ0VjUS6i8j56LYkPwOseq7V66YT)

**Comment by dangercrow** [comment]
Look into using some tooling e.g. AutoTrimps. There's a branch of that that has no automation too, but only graphs.

Also, linking images is not the best practice because the host might go down (e.g. like it has now)

Better to upload it directly here.

**Comment by Rubik43** [comment]
ok, i didn't know that external tools existed, thanks
