### ISSUE TITLE
Newest Scientist Challenge Impossible

### ISSUE THREAD

**Issue by QuadeHale** [Trimps/Trimps.github.io#24]
On the newest Scientist challenge, you start with 70 science. Scientists become 'unlocked' when you complete it, but you require 100 science to actually unlock the upgrade that unlocks the scientists, thus making it (presumably) overly lengthy and difficult (if not impossible) to reach the point you can Portal again.

I would recommend that across all of the Scientist challenges (or other challenges that lock a job/building/resource), that the relevant job/building/resource is 'auto-purchased' upon completing the challenge.

**Comment by Trimps** [comment]
The button to manually research science immediately reappears after completing a scientist challenge, and two messages pop up in red in the message log stating that you can manually research again. This shouldn't be an issue!-------- Original message --------From: QuadeHale <notifications@github.com> Date: 2/25/2016  2:15 PM  (GMT-08:00) To: "Trimps/Trimps.github.io" <Trimps.github.io@noreply.github.com> Subject: [Trimps.github.io] Newest Scientist Challenge Impossible (#24) 
On the newest Scientist challenge, you start with 70 science. Scientists become 'unlocked' when you complete it, but you require 100 science to actually unlock the upgrade that unlocks the scientists, thus making it (presumably) overly lengthy and difficult (if not impossible) to reach the point you can Portal again.

I would recommend that across all of the Scientist challenges (or other challenges that lock a job/building/resource), that the relevant job/building/resource is 'auto-purchased' upon completing the challenge.

**Comment by QuadeHale** [comment]
The issue is you can't train Scientists until you buy an upgrade, and the upgrade costs 100 science.

**Comment by Trimps** [comment]
But you can click the button that says "Research", right under where you see how much science you have to very quickly gain that 100 science, just like at the start of a fresh run!

**Comment by subchannel13** [comment]
By the time the player can take Science IV challenge he/she should be very familiar with the game, know how to recover from challenge limitations and preferably have completed Science III challenge. Getting 100 science point "manually" takes 100 seconds (less then 2 minutes) at most. That's not overly lengthy period of time. Unless the player has encountered a bug that prevents normal accumulation of science points after completing the challenge, this issue should be considered invalid.

**Comment by QuadeHale** [comment]
You guys are absolutely right. I feel like a buffoon. It's been so long since I had to actually click on any resource production I forgot I could do it.
