### ISSUE TITLE
Equipment upgrade tooltips are incorrect

### ISSUE THREAD

**Issue by pie3636** [Trimps/Trimps.github.io#25]
When hovering over an equipment upgrade, the tooltip always displays "...this will bring your *item* to level 1", regardless of the level.

Image proof : http://i.imgur.com/MvXoXD6.png

**Comment by Trimps** [comment]
And it always does bring your equipment to level 1! This is important and
accurate info to have in the tooltip for prestiges, what's the issue?

**Comment by pie3636** [comment]
My bad, I thought you were referring to the prestige level, and it was always displaying "1" instead of the correct level. Sorry for the inconvenience!
May I suggest adding a little "back" in there? As in, "brings your *item* **back** to level 1"? I feel like this would be clear the confusion if anyone else ever has it.
