### ISSUE TITLE
Buttons hidden on ultra-wide monitors

### ISSUE THREAD

**Issue by kix2902** [Trimps/Trimps.github.io#26]
In ultra-wide monitors (form factor 21:9) some buttons ("Repeat" and "Trade Bones") get hidden in the map zone when the browser is in expanded mode

![snip_20160316134331](https://cloud.githubusercontent.com/assets/222587/13812605/5c51200a-eb7d-11e5-87fb-1ae83a70b12a.png)

**Comment by Trimps** [comment]
Yes, trimps does not run on aspect ratios where the width is more than twice the height. Try shrinking the width of the page!-------- Original message --------From: Ismael Reyes <notifications@github.com> Date: 3/16/2016  5:48 AM  (GMT-08:00) To: "Trimps/Trimps.github.io" <Trimps.github.io@noreply.github.com> Subject: [Trimps.github.io] Buttons hidden on ultra-wide monitors (#26) 
In ultra-wide monitors (form factor 21:9) some buttons ("Repeat" and "Trade Bones") get hidden in the map zone when the browser is in expanded mode
