### ISSUE TITLE
Bad wording on completing "Scientist" challenges

### ISSUE THREAD

**Issue by ikacnep** [Trimps/Trimps.github.io#28]
main.js:750 && config.js:2810 --- "...From now on, you will **receive earn** two levels of each prestige...". I've only noticed it on Scientist IV, but it seems to be on all Scientist challenges.

I'd suppose removing word "receive" from config.js:2810, as each Scientist description starts with a verb already. I'm new to gihub (I've registered only to report this ;) ), so I don't know how to fix it myself.

**Comment by Trimps** [comment]
This was fixed a few patches ago, thanks!
