### ISSUE TITLE
corruptDodge is 33% not 30%.

### ISSUE THREAD

**Issue by finite2** [Trimps/Trimps.github.io#35]
The code for the dodging corrupt enemies lets them dodge more than the stated 30%.

This code appears on line 4665 of main.js:
```{js}
if (cell.corrupted == "corruptDodge"){
		if (Math.floor(Math.random() * 3) == 0) badDodge = true;
	}
```

The below code would both simplify the code and correct this.

```{js}
if (cell.corrupted == "corruptDodge"){
		if (Math.random() < 0.3) badDodge = true;
	}
```

**Comment by Trimps** [comment]
Fixed, thanks!
