### ISSUE TITLE
Number of workers can occasionally have trailing zero (minor)

### ISSUE THREAD

**Issue by dunctait** [Trimps/Trimps.github.io#37]
For instance, I can have 1.7 million wood workers, but 1.70 million metal workers.

It's something to do with the rounding because if I fire a few thousand metal workers then it changes to 1.7 million

This is not a large issue but it annoys me for reasons I can't explain

**Comment by Grimy** [comment]
I made a few tests:

* Up to 1699499, `1.69M` is shown
* From 1699500 to 1700500, `1.7M` is shown
* From 1700501 to 1709499, `1.70M` is shown
* For 1709500 and above, `1.71M` is shown

I agree that this behavior is weird and could use some tweaks.
