### ISSUE TITLE
Price per item

### ISSUE THREAD

**Issue by NookieGrey** [Trimps/Trimps.github.io#39]
Often, when i looking for new building or upgrade, i calculate in mind price per item for better purchase. So I write small patch, that do it for me:

https://gist.github.com/NugzarGaguliya/316dd1a945ebcb6cb263be7fabcfe6df

It will be cool to see something that in settings:
- Show total price
- Show price per item

**Comment by Trimps** [comment]
This doesn't accurately calculate price per item, as prices increase exponentially. Buying 25 of a building for 100 wood does not mean you're paying 4 wood each!

**Comment by NugzarGaguliya** [comment]
Yes, it's calculate only for one item
