### ISSUE TITLE
game.global.maxSplit == 0.33 !== 1/3

### ISSUE THREAD

**Issue by NugzarGaguliya** [Trimps/Trimps.github.io#40]
For example i have 3195 workers
and i whant distributed them equally between 3 positions
fisrt i run 0.33
then 0.5
and others
3196%3=0, so it must be 1065 in each position
but in code we calculate first step by Math.floor(3196*0.33) = 1054

it will be cool to calculate Math.floor(n/3), not Math.floor(n*0.33)

**Comment by Trimps** [comment]
Try typing 1/3 in the custom box instead of 0.33 :)
