### ISSUE TITLE
Blockmaster inconsistent description/effect

### ISSUE THREAD

**Issue by CookiesBestDinner** [Trimps/Trimps.github.io#44]
Description says the increase is 1.5x, but the increase is 0.5x

**Comment by subchannel13** [comment]
No, it's consistent, increase is +50% or factor of 1.5. 1.5x means something is multiplied by one and half and since 4 * 1.5 = 6 the description text is correct.

**Comment by CookiesBestDinner** [comment]
It's not. Saying that the increase is 150% means that 150% is added.

**Comment by namedots** [comment]
Some formation descriptions are doing this same thing.
example:

> Trimps gain 4x attack but lose half of their health and block.

(gaining 4x would result in 5x)
