### ISSUE TITLE
Problem with external site data

### ISSUE THREAD

**Issue by jerith** [Trimps/Trimps.github.io#6]
I have my web browser configured to block external site data, which causes problems when I play the game on Kongregate, the most obvious of which is an inability to save. (I was also unable to gather food when I first started the game. I don't remember if this was related to local storage or not, though.)

I don't know enough JS to provide a patch, but it may be possible to detect this and suggest changing the relevant browser settings. Alternatively, some general troubleshooting suggestions whenever saving fails might be helpful.

Thanks for the game!

**Comment by jHoyne** [comment]
what happens when it is played outside of Kongregate like at the trimps.io http://trimps.github.io/

**Comment by jerith** [comment]
The stored data is associated with the `trimps.github.io` domain, because that's where the JS code is hosted. If you play the game from that domain, there's no problem with external site data (because it's not external). Both sites use the same saved game, which is nice. :-)
