### ISSUE TITLE
Priority Crafting que 

### ISSUE THREAD

**Issue by jHoyne** [Trimps/Trimps.github.io#7]
330K traps takes a long time and I decided to upgrade the forge so I have more metal available but it is going to take forever to do that with 10 Foreman and me helping to build maybe a priority crafting system is necessary.

**Comment by FlyingKumquat** [comment]
Personally, I just cancel whatever is ahead of what I need built right away. You get refunded full material costs.

**Comment by jHoyne** [comment]
Yeah but with the order cap at 15k it gets annoying to reorder 330K so maybe what about a moving option

**Comment by FlyingKumquat** [comment]
Why do you have a queue of traps anyways? Patch 1.05 added the upgrade "Trapstorm", found from any level 10+ map, that lets you enable/disable auto-building traps while your queue is empty.

**Comment by jHoyne** [comment]
I wanted to see how long it took and trapstorm gets is odd when you cannot produce the 250 food and wood needed to make them so it is more efficient in my case to just order them

**Comment by FlyingKumquat** [comment]
What makes it odd when you don't have the resources (10 food, 10 wood) to make a trap? Is there some sort of bug you are encountering?

**Comment by jHoyne** [comment]
I might have been I've reloaded since then though so if I was I'm unsure

**Comment by jHoyne** [comment]
still priority crafting would be nice

**Comment by QuadeHale** [comment]
There should never be a need for priority crafting.
